# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 20:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=30)),
                ('prereq', models.IntegerField(default=-1)),
                ('syllabus', models.CharField(max_length=500)),
                ('approved', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Enrolls',
            fields=[
                ('enrolls_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maggulater.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('Lecture_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Time', models.DateTimeField(default=datetime.datetime(2016, 3, 9, 20, 15, 52, 407555))),
                ('Topic', models.CharField(default='Topic Not Mentioned', max_length=100)),
                ('Link', models.CharField(max_length=100)),
                ('Course_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maggulater.Course')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('link_to_dp', models.CharField(max_length=100)),
                ('type_flag', models.IntegerField(default=1)),
                ('dob', models.DateField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2016, 3, 9, 20, 15, 52, 416852))),
                ('message', models.CharField(max_length=500)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maggulater.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Performance_Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('Test_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Lecture_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maggulater.Lecture')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Admin_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='maggulater.MyUser')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('Faculty_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='maggulater.MyUser')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='maggulater.MyUser')),
            ],
        ),
        migrations.AddField(
            model_name='performance_sheet',
            name='Test_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maggulater.Test', unique=True),
        ),
        migrations.AddField(
            model_name='performance_sheet',
            name='Student_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maggulater.Student', unique=True),
        ),
        migrations.AddField(
            model_name='enrolls',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maggulater.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maggulater.Faculty'),
        ),
    ]
