# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maggulater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='Topic',
            field=models.CharField(default='Topic Not Mentioned', max_length=100),
        ),
    ]
