# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 23:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maggulater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='totalMarks',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='admin',
            name='Admin_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='maggulater.MyUser'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='Faculty_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='maggulater.MyUser'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 9, 23, 12, 51, 445828)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 9, 23, 12, 51, 453542)),
        ),
        migrations.AlterField(
            model_name='student',
            name='Student_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='maggulater.MyUser'),
        ),
    ]
