# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 00:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maggulater', '0002_auto_20160309_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='Admin_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='maggulater.MyUser'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='Faculty_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='maggulater.MyUser'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 10, 0, 4, 26, 985884)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notice',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 10, 0, 4, 26, 994241)),
        ),
        migrations.AlterField(
            model_name='student',
            name='Student_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='maggulater.MyUser'),
        ),
    ]
