# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 07:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maggulater', '0004_auto_20160310_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance_sheet',
            name='Marks_Obtained',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='performance_sheet',
            name='Marks_Total',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='admin',
            name='Admin_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='maggulater.MyUser'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='Faculty_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='maggulater.MyUser'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 10, 7, 24, 16, 504449)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 10, 7, 24, 16, 508514)),
        ),
        migrations.AlterField(
            model_name='student',
            name='Student_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='maggulater.MyUser'),
        ),
    ]
